from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "public" / "images" / "document-1-project-brief-final.png"

WIDTH = 900
HEIGHT = 1274
PAGE_X = 6
PAGE_Y = 4
PAGE_WIDTH = 888
PAGE_HEIGHT = 1264
SCALE = PAGE_WIDTH / 210.0

FONT_REGULAR = "C:/Windows/Fonts/tahoma.ttf"
FONT_BOLD = "C:/Windows/Fonts/tahomabd.ttf"


def load_font(size, bold=False):
    return ImageFont.truetype(FONT_BOLD if bold else FONT_REGULAR, size)


def mmx(value):
    return PAGE_X + value * SCALE


def mmy(value):
    return PAGE_Y + value * SCALE


def draw_text(draw, text, x, y, fill="#475569", size=20, bold=False, anchor="la"):
    draw.text((mmx(x), mmy(y)), text, fill=fill, font=load_font(size, bold), anchor=anchor)


def draw_line(draw, x1, y1, x2, y2, fill, width=4):
    draw.line([mmx(x1), mmy(y1), mmx(x2), mmy(y2)], fill=fill, width=width)


def draw_rect(draw, x, y, width, height, fill, outline, line_width=3):
    draw.rectangle(
        [mmx(x), mmy(y), mmx(x + width), mmy(y + height)],
        fill=fill,
        outline=outline,
        width=line_width,
    )


def render_preview():
    image = Image.new("RGB", (WIDTH, HEIGHT), "#111111")
    draw = ImageDraw.Draw(image)

    for offset, color in [(8, "#222222"), (4, "#333333")]:
        draw.rectangle(
            [
                PAGE_X + offset,
                PAGE_Y + offset,
                PAGE_X + PAGE_WIDTH + offset,
                PAGE_Y + PAGE_HEIGHT + offset,
            ],
            fill=color,
        )

    draw.rectangle([PAGE_X, PAGE_Y, PAGE_X + PAGE_WIDTH, PAGE_Y + PAGE_HEIGHT], fill="white")

    draw_text(draw, "Project Brief", 20, 24, fill="#111827", size=26)
    draw_text(draw, "2026-06-13", 190, 24, fill="#64748b", size=13, anchor="ra")
    draw_line(draw, 20, 32, 190, 32, "#2457d6", 4)

    card_fill = "#f8fafc"
    card_border = "#cbd5e1"
    draw_rect(draw, 20, 44, 170, 44, card_fill, card_border, 3)
    draw_rect(draw, 20, 106, 170, 56, card_fill, card_border, 3)
    draw_rect(draw, 20, 178, 170, 64, card_fill, card_border, 3)

    image_x = 150
    image_y = 54
    draw_rect(draw, image_x, image_y, 36, 24, "#ffffff", "#d8e1ec", 2)
    draw.rounded_rectangle(
        [mmx(image_x + 2), mmy(image_y + 3), mmx(image_x + 15), mmy(image_y + 18)],
        radius=4,
        fill="#dbeafe",
    )
    draw.ellipse(
        [mmx(image_x + 4), mmy(image_y + 5), mmx(image_x + 8), mmy(image_y + 9)],
        fill="#2563eb",
    )
    draw.polygon(
        [
            (mmx(image_x + 4), mmy(image_y + 17)),
            (mmx(image_x + 9), mmy(image_y + 11)),
            (mmx(image_x + 15), mmy(image_y + 18)),
        ],
        fill="#16a34a",
    )
    draw_line(draw, image_x + 18, image_y + 6, image_x + 30, image_y + 6, "#111827", 3)
    draw_line(draw, image_x + 18, image_y + 10, image_x + 30, image_y + 10, "#64748b", 3)
    draw_line(draw, image_x + 18, image_y + 14, image_x + 28, image_y + 14, "#64748b", 3)
    draw.rounded_rectangle(
        [mmx(image_x + 18), mmy(image_y + 17), mmx(image_x + 24), mmy(image_y + 20)],
        radius=3,
        fill="#2563eb",
    )
    draw.rounded_rectangle(
        [mmx(image_x + 26), mmy(image_y + 17), mmx(image_x + 31), mmy(image_y + 20)],
        radius=3,
        fill="#e2e8f0",
    )
    draw_text(draw, "Sample image path", image_x + 4, image_y + 22, fill="#64748b", size=6)

    draw_text(draw, "ข้อมูลโปรเจกต์", 28, 58, fill="#111827", size=24)
    draw_text(draw, "สรุปภาพรวม", 28, 120, fill="#111827", size=24)
    draw_text(draw, "หมุดหมายงาน", 28, 192, fill="#111827", size=24)

    body_color = "#64748b"
    draw_text(draw, "ชื่อ: บทเรียน jsPDF แบบเห็นภาพ", 28, 74, fill=body_color, size=16)
    draw_text(draw, "เจ้าของ: ทีมเรียนรู้", 28, 82, fill=body_color, size=16)
    draw_text(draw, "สถานะ: พร้อมตรวจทาน", 94, 82, fill=body_color, size=16)

    summary_lines = [
        "พื้นที่ฝึกสร้าง PDF ที่ค่อย ๆ ประกอบเอกสารหนึ่งใบจากหน้าเปล่า ไปสู่เอกสาร Project Brief ที่มีข้อมูล",
        "รูปภาพ สไตล์ และรายการหมุดหมายครบถ้วน",
        "เพื่อให้ผู้เรียนเห็นว่าเอกสารจริงเกิดจากการวางองค์ประกอบหลายส่วนร่วมกัน",
    ]
    for index, line in enumerate(summary_lines):
        draw_text(draw, line, 28, 136 + index * 8, fill=body_color, size=17)

    milestone_lines = [
        "พื้นฐาน: หน้าเอกสาร ข้อความ กล่อง และ style",
        "เนื้อหา: รูปภาพ ฟอนต์ไทย ข้อมูล และการ wrap",
        "ตรวจทาน: ทาบ preview กับ blueprint แล้วปรับตำแหน่ง",
    ]
    for index, line in enumerate(milestone_lines):
        draw_text(draw, line, 28, 208 + index * 10, fill=body_color, size=17)

    draw_line(draw, 20, 270, 190, 270, "#cbd5e1", 3)
    draw_text(draw, "Generated by jsPDF Visual Lesson Playground", 20, 278, fill="#64748b", size=13)

    image.save(OUTPUT_PATH)


if __name__ == "__main__":
    render_preview()
    print(f"wrote {OUTPUT_PATH}")
